
import Head from "next/head";
import { useState } from "react";
import { signInWithEmailAndPassword } from "firebase/auth";
import { auth } from "../firebase/config";
import { useRouter } from "next/router";
import styles from "../styles/Home.module.css";

export default function Home() {
  const [email, setEmail] = useState("");
  const [pass, setPass] = useState("");
  const [error, setError] = useState("");
  const router = useRouter();
  const handleLogin = async (e) => {
    e.preventDefault();
    try {
      const userCred = await signInWithEmailAndPassword(auth, email, pass);
      const token = await userCred.user.getIdTokenResult(true);
      if (token.claims.admin) {
        router.push("/admin-panel");
      } else {
        setError("Access denied: Not an admin.");
      }
    } catch (err) {
      setError("Login failed.");
    }
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <form onSubmit={handleLogin}>
          <h2>Admin Login</h2>
          <input value={email} onChange={e => setEmail(e.target.value)} placeholder="Email" />
          <input type="password" value={pass} onChange={e => setPass(e.target.value)} placeholder="Password" />
          <button type="submit">Login</button>
          <p style={{ color: "red" }}>{error}</p>
        </form>
      </main>
    </div>
  );
};
